### ISSUE TITLE
Cloak of Frostology does not work with the Accessories mod

### ISSUE THREAD

**Issue by leotheshade** [TheDeathlyCow/frostiful#111]
**Describe the bug**
When equipping the Cloak of Frostology to the "Cape" slot using Blodhgarm's Accessory Mod, the Cloak does not function as it should and has no effects.

**To Reproduce**
1. Equip Cloak of Frostology to the "Cape" slot

**Expected behavior**
The Cloak of Frostology applies it's "Become ice-like" effect while freeing up the chest slot for another chestplate.

**Game information (please complete)**
- MC Version 1.20.1
- Loader: Fabric using Curseforge

**Additional context**
Mod is used in the Prominence II RPG Hasturian Era modpack.

**Comment by TheDeathlyCow** [comment]
The Frostology Cloak cape was integrated with Trinkets, not Accessories. However, Accessories has a compatibility layer for Trinkets: https://modrinth.com/mod/accessories-tc-layer

**Comment by TheDeathlyCow** [comment]
Sorry just re-read this issue. In 1.20.1, this is a documented and expected behaviour of the Frostology Cloak. The cape slot is meant to be purely cosmetic, while the chest slot is functional. In this 1.21.1, this was changed so that a separate Inert Frostology Cloak is purely cosmetic, but when activated by a Glacial Heart it gets the ice-born powers. This change will not be backported to 1.20.
