### ISSUE TITLE
[Mod Compat]  Deserts do not 'passive freeze' in winter with Fabric Seasons installed

### ISSUE THREAD

**Issue by MLMII** [TheDeathlyCow/frostiful#26]
With the seasons mod installed night time passive freezing in deserts appears to work during Spring, Summer, and Fall; but not during Winter for some reason.

Thank you for your time.

**Comment by TheDeathlyCow** [comment]
I'd guess that Fabric Seasons allowed deserts to rain in the winter. The desert freezing works based on whether the biome is dry or not. This is based on how in real life, dry biomes hold less moisture, which means at night the heat isn't held very well, and so they are much colder. Perhaps then, this isn't a compatibility issue but actually it works as intended. Hard to say though since winter is of course, supposed to be cold.

**Comment by MLMII** [comment]
Thank you for the response; that makes a lot of sense considering how the mods interact.
