### ISSUE TITLE
Suggestion: Enchantment that decreases the effect of gusts of wind pushing the player.

### ISSUE THREAD

**Issue by zenmastersloth** [TheDeathlyCow/frostiful#69]
Just came to make a suggestion that came up in discussion in the Better Minecraft modpack community. I would love it if there was an enchantment in Frostful like "Sure Footing" for you boots or something that decreases the amount gusts of wind effect the player with each level. Love the mod. Makes things interesting for sure.

**Comment by TheDeathlyCow** [comment]
I think maybe one way to go about adding something like this would be to have the wind apply a more traditional knockback effect, so that the knockback resistance attribute can be applied. It does basically the same thing and doesn't involve duplicating game elements which could be confusing for players.
